#!/usr/bin/env bash
# Script: story based on /etc/passwd
# Displays formatted information using while loop + IFS

while IFS=: read -r username password userid groupid info home shell
do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $username's place is protected by the passcode $password, more info about the user here: $userid $info"
done < /etc/passwd
