#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# and prints special messages for 4, 9, and 17 using a while loop and case statement

supern=1

while [ $supern -le 20 ]
do
	case $supern in
		4)
			echo "$supern"
			echo "bad luck from China"
			;;
		9)
			echo "$supern"
			echo "bad luck from Japan"
			;;
		17)
			echo "$supern"
			echo "bad luck from Italy"
			;;
		*)
			echo "$supern"
			;;
		esac
		((supern++))
	done
