#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
# Using a while loop (for and until are forbidden)

hour=0

while [ $hour -le 12 ]
do
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$hour:$minutes"
		((minutes++))
	done
	((hour++))
done
