#!/bin/bash
SUM=0; for ((i=0;i<${#WATER};i++)); do case ${WATER:i:1} in w) v=0;;a) v=1;;t) v=2;;e) v=3;;r) v=4;;esac; SUM=$((SUM*5+v)); done; for ((i=0;i<${#STIR};i++)); do case ${STIR:i:1} in t) v=0;;i) v=1;;.) v=2;;r) v=3;;esac; SUM=$((SUM*5+v)); done; OUT=""; BASE="bestchol"; while ((SUM>0)); do OUT=${BASE:SUM%9:1}$OUT; SUM=$((SUM/9)); done; echo $OUT
