#!/bin/bash
echo $(( $(echo $WATER | fold -w1 | awk '{c=substr("water",index("water",$1),1)?index("water",$1)-1:0} END{print c}' ) + $(echo $STIR | fold -w1 | awk '{c=substr("stir",index("stir",$1),1)?index("stir",$1)-1:0} END{print c}' ) )) 
